from turtles_cli.audits import ai_detect, context_usage


def test_context_usage_returns_claude_style_categories() -> None:
    usage = context_usage(["hello world"], window=200_000, model="test-model")

    assert usage["model"] == "test-model"
    assert usage["window"] == 200_000
    assert usage["categories"]["system_prompt"] > 0
    assert usage["autocompact_buffer"] > 0


def test_ai_detect_scores_generated_style_markers(tmp_path) -> None:
    source = tmp_path / "generated.py"
    source.write_text(
        "# Generated by AI\n"
        "def run():\n"
        "    # Step 1: ensure that the workflow is robust\n"
        "    return 'mock implementation'\n",
        encoding="utf-8",
    )

    estimate, findings = ai_detect(tmp_path)

    assert estimate > 0
    assert findings
