from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path


TEXT_EXTENSIONS = {
    ".py",
    ".js",
    ".ts",
    ".tsx",
    ".jsx",
    ".go",
    ".rs",
    ".java",
    ".cs",
    ".rb",
    ".php",
    ".md",
    ".toml",
    ".yaml",
    ".yml",
    ".json",
    ".env",
    ".sh",
    ".ps1",
    ".dockerfile",
}

SECRET_PATTERNS = [
    re.compile(r"sk-[A-Za-z0-9_-]{20,}"),
    re.compile(r"ghp_[A-Za-z0-9]{20,}"),
    re.compile(r"AKIA[0-9A-Z]{16}"),
    re.compile(r"(?i)(api[_-]?key|secret|token|password)\s*[:=]\s*['\"]?[^'\"\s]{12,}"),
]

AI_MARKERS = [
    "generated by ai",
    "ai-generated",
    "as an ai language model",
    "as a large language model",
    "generated by chatgpt",
    "chatgpt generated",
    "claude generated",
    "generated by claude",
    "generated with claude",
    "generated with copilot",
    "copilot generated",
    "generated with windsurf",
    "windsurf generated",
    "TODO: implement this function",
]

AI_STYLE_PATTERNS = [
    (re.compile(r"\bplaceholder\b|\bmock implementation\b|\bstub implementation\b", re.I), 1.0, "Placeholder or stub wording."),
    (re.compile(r"^\s*(#|//|/\*)\s*(Step \d+|First,|Next,|Finally,)", re.I), 0.8, "Step-by-step generated-comment style."),
]


@dataclass
class Finding:
    path: str
    line: int
    severity: str
    message: str


def iter_project_files(root: Path, target: str | None = None) -> list[Path]:
    if target:
        path = (root / target).resolve()
        return [path] if path.is_file() else [p for p in path.rglob("*") if p.is_file()]
    ignored = {".git", ".venv", "node_modules", ".turtles", "__pycache__", "dist", "build"}
    files: list[Path] = []
    for path in root.rglob("*"):
        if not path.is_file():
            continue
        if any(part in ignored for part in path.parts):
            continue
        if path.suffix.lower() in TEXT_EXTENSIONS or path.name.lower() in {"dockerfile", "compose.yml", "docker-compose.yml"}:
            files.append(path)
    return files


def safe_read(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        return path.read_text(encoding="utf-8", errors="ignore")


def code_review(root: Path, target: str | None = None) -> list[Finding]:
    findings: list[Finding] = []
    for path in iter_project_files(root, target):
        text = safe_read(path)
        lines = text.splitlines()
        if len(lines) > 800:
            findings.append(Finding(str(path.relative_to(root)), 1, "info", "Large file; consider splitting or targeted review."))
        for index, line in enumerate(lines, start=1):
            lowered = line.lower()
            if "todo" in lowered or "fixme" in lowered:
                findings.append(Finding(str(path.relative_to(root)), index, "low", "TODO/FIXME marker needs triage."))
            if "except:" in line:
                findings.append(Finding(str(path.relative_to(root)), index, "medium", "Bare except hides errors."))
            if "eval(" in line or "exec(" in line:
                findings.append(Finding(str(path.relative_to(root)), index, "high", "Dynamic execution requires careful validation."))
    return findings


def security_audit(root: Path, target: str | None = None) -> list[Finding]:
    findings: list[Finding] = []
    for path in iter_project_files(root, target):
        for index, line in enumerate(safe_read(path).splitlines(), start=1):
            for pattern in SECRET_PATTERNS:
                if pattern.search(line):
                    findings.append(Finding(str(path.relative_to(root)), index, "critical", "Possible secret or credential in source."))
                    break
            lowered = line.lower()
            if "verify=false" in lowered or "strictssl false" in lowered:
                findings.append(Finding(str(path.relative_to(root)), index, "high", "TLS verification appears disabled."))
    return findings


def docker_audit(root: Path) -> list[Finding]:
    findings: list[Finding] = []
    dockerfiles = [p for p in root.rglob("Dockerfile") if ".git" not in p.parts]
    compose_files = [p for p in root.rglob("*compose*.yml") if ".git" not in p.parts] + [p for p in root.rglob("*compose*.yaml") if ".git" not in p.parts]
    for path in dockerfiles:
        lines = safe_read(path).splitlines()
        if not lines:
            findings.append(Finding(str(path.relative_to(root)), 1, "high", "Dockerfile is empty."))
            continue
        for index, line in enumerate(lines, start=1):
            stripped = line.strip()
            if stripped.upper().startswith("FROM ") and ":latest" in stripped:
                findings.append(Finding(str(path.relative_to(root)), index, "medium", "Avoid latest tags; pin a stable base image version."))
            if stripped.upper().startswith("USER root"):
                findings.append(Finding(str(path.relative_to(root)), index, "medium", "Running as root increases container risk."))
    for path in compose_files:
        text = safe_read(path)
        if "version:" in text:
            findings.append(Finding(str(path.relative_to(root)), 1, "info", "Compose version field is optional in modern Docker Compose."))
    if not dockerfiles and not compose_files:
        findings.append(Finding(".", 1, "info", "No Dockerfile or Compose files found."))
    return findings


def ai_detect(root: Path) -> tuple[int, list[Finding]]:
    files = iter_project_files(root)
    total_lines = 0
    weighted_score = 0.0
    flagged_files: set[Path] = set()
    findings: list[Finding] = []
    seen: set[tuple[str, int, str]] = set()
    for path in files:
        for index, line in enumerate(safe_read(path).splitlines(), start=1):
            total_lines += 1
            lowered = line.lower()
            relative = str(path.relative_to(root))
            line_reasons: list[tuple[float, str]] = []
            if any(marker in lowered for marker in AI_MARKERS):
                line_reasons.append((2.0, "Explicit AI-generated marker or boilerplate phrase."))
            if len(line) > 180 and ("because" in lowered or "therefore" in lowered):
                line_reasons.append((0.8, "Long explanatory line with generated-text style connectors."))
            for pattern, weight, message in AI_STYLE_PATTERNS:
                if pattern.search(line):
                    line_reasons.append((weight, message))
                    break
            if not line_reasons:
                continue
            weighted_score += max(weight for weight, _message in line_reasons)
            flagged_files.add(path)
            message = "; ".join(dict.fromkeys(message for _weight, message in line_reasons))
            key = (relative, index, message)
            if key not in seen and len(findings) < 120:
                seen.add(key)
                findings.append(Finding(relative, index, "info", message))
    line_density = (weighted_score / max(total_lines, 1)) * 400
    file_density = (len(flagged_files) / max(len(files), 1)) * 20
    estimate = min(100, round(line_density + file_density))
    return estimate, findings


def context_usage(messages: list[str] | None = None, *, window: int = 128_000, model: str = "model") -> dict[str, object]:
    messages = messages or []
    message_tokens = sum(max(1, len(message) // 4) for message in messages)
    categories = {
        "system_prompt": 2_600,
        "system_tools": 17_600,
        "mcp_tools": 900,
        "custom_agents": 900,
        "memory_files": 300,
        "skills": 100,
        "messages": message_tokens,
    }
    used = sum(categories.values())
    autocompact_buffer = round(window * 0.165)
    return {
        "used": used,
        "remaining": max(0, window - used - autocompact_buffer),
        "window": window,
        "segments": len(messages),
        "model": model,
        "categories": categories,
        "autocompact_buffer": autocompact_buffer,
    }
